version: '3.5'
services:
  proxy:
    build: ./reverse-proxy
    ports:
      - "8080:8080"
  balance:
    build:
      context: .
      dockerfile: ./balance-server-mock/Dockerfile
  customer-details:
    build:
      context: .
      dockerfile: ./customer-details-server-mock/Dockerfile
